project:
  type: book

book:
  title: "Ideas Canvas"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/idea-canvas
  site-url: https://idea-canvas-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: IDE
      chapters: 
        - "content/IDE/ide-concept.qmd"
    - part: Text Editor
      chapters: 
        - "content/TextEditor/editor-dev-guilde.md"
        - "content/TextEditor/editor-radio-guide.md"
    - part: CNN
      chapters: 
        - "content/DL/Deploy-CNN-Edge-US.qmd"
    - part: LLM
      chapters: 
        - "content/LLM/llm-enterprise-architect.qmd"
    - part: Radio Platform
      chapters: 
        - "content/RadioPlatform/radiology_assist_platform.qmd"
    - part: DICOM OpenQR
      chapters: 
        - text: Architecture
          href: "content/DICOM-QR/dicom-qr-app.qmd"
        - text: DicomOpenQR (PRD)
          href: "content/DICOM-QR/DicomOpenQR-PRD.qmd"
        - text: DicomOpenQR (Architecture)
          href: "content/DICOM-QR/DicomOpenQR-Architecture.qmd"


format:
  html:
    theme:
      - cosmo
      - brand



